### ISSUE TITLE
"concourse.ci" --> "concourse-ci.org"

### ISSUE THREAD

**Issue by coreyti** [compozed/travel-agent#5]
Hello,

A (strong) suggestion: the README should be updated to replace the "concourse.ci" text with "concourse-ci.org". While it's not a link, project visitors might be inclined to browse to that domain. However, as noted in the following post, the "concourse.ci" domain is no longer owned by the Concourse team and is now a phishing scam: https://medium.com/concourse-ci/were-switchin-domains-5597dcd0b48b

**Comment by geofffranks** [comment]
Fixed in #10
